CREATE DATABASE PATIENTDB;

USE PATIENTDB;

CREATE TABLE PATIENT 
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	PRIMARY KEY (ID)
);

DROP TABLE PATIENT;

DROP DATABASE PATIENTDB;